# Generated by Django 3.0.3 on 2020-07-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app_temp', '0002_auto_20200626_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('text', models.CharField(max_length=264)),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
